### ISSUE TITLE
code not runnable.

### ISSUE THREAD

**Issue by WeiWeic6222848** [KarolisMart/AgentNet#1]
Hi! I have seen your paper and is interested in this new model.
However, the code in this repository can't be executed with the command in readme after I have installed the requirements.
There are some args that can't be parsed and some args that are too much, what should I do to reproduce the results in paper?
some errors I encountered:
```Traceback (most recent call last):
  File "C:\Users\..\AgentNet\ogb_mol.py", line 267, in <module>
    main(args)
  File "C:\Users\..\AgentNet\ogb_mol.py", line 160, in main
    sparse_conv=args.sparse_conv, num_edge_features=args.num_edge_features, mean_pool_only=args.mean_pool_only, edge_negative_slope=args.edge_negative_slope,
AttributeError: 'TTNamespace' object has no attribute 'num_edge_features'
Traceback (most recent call last):
  File "..\AgentNet\ogb_mol.py", line 267, in <module>
    main(args)
  File "..\AgentNet\ogb_mol.py", line 161, in main
    regression=args.regression, final_readout_only=args.final_readout_only, ogb_mol=True).to(device)
AttributeError: 'TTNamespace' object has no attribute 'regression'
```

**Comment by KarolisMart** [comment]
Hi. Before doing the initial commit I did some quick cleanup that apparently messed stuff up. I pushed an update and now things should work.
Thanks for raising this!
Note that in the final version of the paper we added a few extra experiments in the appendix (ZINC, OGB PPA), which are not in the repo yet, but hopefully I'll come around adding them here in the next few weeks.

**Comment by WeiWeic6222848** [comment]
Thank you! I can run the experiment now!
