### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'device'

### ISSUE THREAD

**Issue by AILUOMANGALAOSHI** [KarolisMart/AgentNet#2]
Traceback (most recent call last):
  File "graph_classification.py", line 476, in <module>
    main(args)
  File "graph_classification.py", line 398, in main
    train_loss, train_acc, train_aux_acc = train(epoch, train_loader, optimizer)
  File "graph_classification.py", line 328, in train
    logs, aux_logs = model(data.x, data.edge_index, data.batch)
  File "/root/anaconda3/envs/pyg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/AgentNet/model.py", line 333, in forward
    agent_emb = self.agent_emb(torch.arange(self.num_agents, device=edge_index.device)).unsqueeze(0).expand(batch_size, -1, -1).reshape(-1, self.dim)
AttributeError: 'tuple' object has no attribute 'device'

**Comment by KarolisMart** [comment]
Hi, could you tell me what exactly was the command you ran?

**Comment by AILUOMANGALAOSHI** [comment]
> 嗨，你能告诉我你运行的命令到底是什么吗？

python graph_classification.py --dataset 'MUTAG' --verbose --dropout 0.0 --num_agents 18 --num_steps 16 --batch_size 32 --reduce 'log' --hidden_units 128 --epochs 350 --warmup 0 --gumbel_decay_epochs 500 --clip_grad 1.0 --weight_decay 0.01 --self_loops --lr 0.0001 --mlp_width_mult 2 --model_type agent --input_mlp --activation_function 'leaky_relu' --negative_slope 0.01 --gumbel_min_temp 0.66666667 --gumbel_temp 0.66666667 --global_agent_pool --bias_attention

**Comment by KarolisMart** [comment]
This is strange. I'm unable to recreate this error. Are you sure you are using the conda environment from the `environment.yml` file?
It might be that you have a different version of PyTorch Geometric.
See for example this [colab](https://colab.research.google.com/drive/1vA4Ot9xiwexxXGvivKLKoHnudYel0DwG?usp=sharing) where it works as expected.
Note that if you run the colab yourself it will take a while to install the environment.
